export const scenes = [
  {
    id: 'top',
    shortLabel: 'digiVance',
    eyebrow: 'digiVance digital studio',
    title: 'Digital products built for business.',
    body: 'digiVance designs and builds focused digital products that help businesses present, sell and work better.',
    image: '/assets/posters/digivance-world.webp',
    mobileImage: '/assets/posters-mobile/digivance-world.webp',
    video: '/assets/video/dive-01-world.mp4',
    videoPoster: '/assets/video/posters/dive-01-world.webp',
    mobileVideo: '/assets/video-mobile/dive-01-world-m.mp4',
    mobileVideoPoster: '/assets/video-mobile/posters/dive-01-world-m.webp',
    frames: 192,
    mobileFrames: 144,
    imageAlt: 'A connected miniature world joining architecture, timber, print and textile studios',
    align: 'left',
    kind: 'intro',
  },
  {
    id: 'studio-agriya',
    shortLabel: 'Studio Agriya',
    client: 'Studio Agriya',
    type: 'Architecture Portfolio Website',
    title: 'Studio Agriya',
    outcome: 'A visual-first portfolio for architectural work.',
    body: 'Projects, process and enquiries are presented through clear navigation and large imagery.',
    projectUrl: 'https://studio-agriya.vercel.app/',
    projectDomain: 'studio-agriya.vercel.app',
    image: '/assets/posters/studio-agriya.webp',
    mobileImage: '/assets/posters-mobile/studio-agriya.webp',
    video: '/assets/video/dive-02-studio-agriya.mp4',
    videoPoster: '/assets/video/posters/dive-02-studio-agriya.webp',
    mobileVideo: '/assets/video-mobile/dive-02-studio-agriya-m.mp4',
    mobileVideoPoster: '/assets/video-mobile/posters/dive-02-studio-agriya-m.webp',
    frames: 192,
    mobileFrames: 240,
    imageAlt: 'An isometric miniature architecture studio with a model home and material library',
    align: 'left-low',
  },
  {
    id: 'sr-timbers',
    shortLabel: 'SR Timbers',
    client: 'SR Timbers',
    type: 'Digital Business Card',
    title: 'SR Timbers',
    outcome: 'One fast link for the entire business.',
    body: 'The timber range, contact details and enquiry actions are available in one mobile-first profile.',
    projectUrl: 'https://srtimbers.com',
    projectDomain: 'srtimbers.com',
    image: '/assets/posters/sr-timber.webp',
    mobileImage: '/assets/posters-mobile/sr-timber.webp',
    video: '/assets/video/dive-03-sr-timber.mp4',
    videoPoster: '/assets/video/posters/dive-03-sr-timber.webp',
    mobileVideo: '/assets/video-mobile/dive-03-sr-timber-m.mp4',
    mobileVideoPoster: '/assets/video-mobile/posters/dive-03-sr-timber-m.webp',
    frames: 192,
    mobileFrames: 144,
    imageAlt: 'An isometric timber workshop with stacked hardwood and a dark digital business card',
    align: 'right-low',
  },
  {
    id: 'rajlaxmi-prints',
    shortLabel: 'Rajlaxmi Prints',
    client: 'Rajlaxmi Prints',
    type: 'Catalogue Picker',
    title: 'Rajlaxmi Prints',
    outcome: 'Faster print browsing and selection for buyers.',
    body: 'Buyers can browse prints, compare options and share selections without working through a static catalogue.',
    projectUrl: 'https://rajlaxmi-prints.vercel.app',
    projectDomain: 'rajlaxmi-prints.vercel.app',
    image: '/assets/posters/rajlaxmi-prints.webp',
    mobileImage: '/assets/posters-mobile/rajlaxmi-prints.webp',
    video: '/assets/video/dive-04-rajlaxmi-prints.mp4',
    videoPoster: '/assets/video/posters/dive-04-rajlaxmi-prints.webp',
    mobileVideo: '/assets/video-mobile/dive-04-rajlaxmi-prints-m.mp4',
    mobileVideoPoster: '/assets/video-mobile/posters/dive-04-rajlaxmi-prints-m.webp',
    frames: 192,
    mobileFrames: 240,
    imageAlt: 'An isometric print atelier with paper swatches and a central catalogue selection table',
    align: 'left-high',
  },
  {
    id: 'radha-madhav-textiles',
    shortLabel: 'Radha Madhav Textiles',
    client: 'Radha Madhav Textiles',
    type: 'Textile Business Website',
    title: 'Radha Madhav Textiles',
    outcome: 'Products, company information and enquiries in one place.',
    body: 'The textile range is easy to explore, while company details and enquiry actions stay close.',
    projectUrl: 'https://radha-madhav-textiles.vercel.app/',
    projectDomain: 'radha-madhav-textiles.vercel.app',
    image: '/assets/posters/radha-madhav-textiles.webp',
    mobileImage: '/assets/posters-mobile/radha-madhav-textiles.webp',
    video: '/assets/video/dive-05-radha-madhav-textiles.mp4',
    videoPoster: '/assets/video/posters/dive-05-radha-madhav-textiles.webp',
    mobileVideo: '/assets/video-mobile/dive-05-radha-madhav-textiles-m.mp4',
    mobileVideoPoster: '/assets/video-mobile/posters/dive-05-radha-madhav-textiles-m.webp',
    frames: 96,
    mobileFrames: 240,
    imageAlt: 'An isometric textile studio with a loom, fabric rolls and presentation panels',
    align: 'right-high',
  },
  {
    id: 'contact',
    shortLabel: 'Start a project',
    title: 'Need a website or digital product?',
    body: 'Tell us what your business needs. digiVance will turn it into a clear, useful digital solution.',
    image: '/assets/posters/start-a-project.webp',
    mobileImage: '/assets/posters-mobile/start-a-project.webp',
    video: '/assets/video/dive-06-start-a-project.mp4',
    videoPoster: '/assets/video/posters/dive-06-start-a-project.webp',
    mobileVideo: '/assets/video-mobile/dive-06-start-a-project-m.mp4',
    mobileVideoPoster: '/assets/video-mobile/posters/dive-06-start-a-project-m.webp',
    frames: 144,
    mobileFrames: 144,
    imageAlt: 'An open miniature creative worktable where four paths meet beside an inviting doorway',
    align: 'left',
    kind: 'contact',
  },
]

/*
 * Connectors carry 2x the footage frames of the dives per second of camera
 * move: they were motion-interpolated from 144 to 287 frames so the seam
 * travel reads at half the speed of a dive without thinning frame density.
 * Runway is derived from `frames`, so the extra frames slow the transition
 * automatically -- see connectorRunwayVh in ./pacing.
 */
export const connectors = [
  {
    id: 'world-to-agriya',
    from: 'top',
    to: 'studio-agriya',
    video: '/assets/video/connector-01-world-to-agriya.mp4',
    poster: '/assets/video/posters/connector-01-world-to-agriya.webp',
    mobileVideo: '/assets/video-mobile/connector-01-world-to-agriya-m.mp4',
    mobilePoster: '/assets/video-mobile/posters/connector-01-world-to-agriya-m.webp',
    frames: 287,
    mobileFrames: 144,
  },
  {
    id: 'agriya-to-sr-timbers',
    from: 'studio-agriya',
    to: 'sr-timbers',
    video: '/assets/video/connector-02-agriya-to-sr-timber.mp4',
    poster: '/assets/video/posters/connector-02-agriya-to-sr-timber.webp',
    mobileVideo: '/assets/video-mobile/connector-02-agriya-to-sr-timber-m.mp4',
    mobilePoster: '/assets/video-mobile/posters/connector-02-agriya-to-sr-timber-m.webp',
    frames: 287,
    mobileFrames: 144,
  },
  {
    id: 'sr-timbers-to-rajlaxmi',
    from: 'sr-timbers',
    to: 'rajlaxmi-prints',
    video: '/assets/video/connector-03-sr-timber-to-rajlaxmi.mp4',
    poster: '/assets/video/posters/connector-03-sr-timber-to-rajlaxmi.webp',
    mobileVideo: '/assets/video-mobile/connector-03-sr-timber-to-rajlaxmi-m.mp4',
    mobilePoster: '/assets/video-mobile/posters/connector-03-sr-timber-to-rajlaxmi-m.webp',
    frames: 287,
    mobileFrames: 144,
  },
  {
    id: 'rajlaxmi-to-textiles',
    from: 'rajlaxmi-prints',
    to: 'radha-madhav-textiles',
    video: '/assets/video/connector-04-rajlaxmi-to-textiles.mp4',
    poster: '/assets/video/posters/connector-04-rajlaxmi-to-textiles.webp',
    mobileVideo: '/assets/video-mobile/connector-04-rajlaxmi-to-textiles-m.mp4',
    mobilePoster: '/assets/video-mobile/posters/connector-04-rajlaxmi-to-textiles-m.webp',
    frames: 287,
    mobileFrames: 192,
  },
  {
    id: 'textiles-to-finale',
    from: 'radha-madhav-textiles',
    to: 'contact',
    video: '/assets/video/connector-05-textiles-to-finale.mp4',
    poster: '/assets/video/posters/connector-05-textiles-to-finale.webp',
    mobileVideo: '/assets/video-mobile/connector-05-textiles-to-finale-m.mp4',
    mobilePoster: '/assets/video-mobile/posters/connector-05-textiles-to-finale-m.webp',
    frames: 287,
    mobileFrames: 192,
  },
]

export const contactEmail = 'hello@digivance.in'
